/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ModalDialog: typeof import('./src/widgets/ModalDialog.vue')['default']
    NumberInput: typeof import('./src/widgets/form/NumberInput.vue')['default']
    Popup: typeof import('./src/widgets/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextButton: typeof import('./src/widgets/form/TextButton.vue')['default']
    TextInput: typeof import('./src/widgets/form/TextInput.vue')['default']
    TextSelect: typeof import('./src/widgets/form/TextSelect.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
